---
#-------------------------------
# General Site Settings

title: DKU_OSS
logo:
author: aen0n
description: this is meta description
email: 32201950@dankook. <br> ac.kr
phone: +82 10 3700 5464
address: 94, Soraeyeok-ro, Namdong-gu, Incheon, Republic of Korea
copyright: Copyright &copy; 2024 Designed & Developed by [aenon](https://github.com/aen0n/Mid-Term-Project)

menu:
  - { name: About, link: "about" }
  - { name: Blog, link: "blog" }
  - { name: Portfolio, link: "portfolio" }
  - { name: Contact, link: "contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> 4enon <br> DKU Student

social:
  - { icon: "ti-instagram", link: "https://www.instagram.com/punchdrunkl0ve_/" }
  - { icon: "ti-dribbble", link: "https://github.com/aen0n/Mid-Term-Project" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: I'm Park Haewon, a software major at Dankook University. I'm currently in the fourth grade, and I'm developing Unreal Engine games as a Capstone project. I'm also interested in developing financial apps and security, and I'm currently working on research on areas of interest.

blurb-btn-link: "about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "We analyze the given problems, create clear objectives, and comprehensively design the plans associated with them. In this step, we mainly map ideas and create suggestions, and specify what development research should be conducted."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Design specific content based on previous suggestions. Development and feedback are repeated within the team during this process, and modifications and updates are used to improve the project."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Disclosure or delivery of completed projects. Multiple patches can allow minor updates, including bug fixes."

# My Team Section
team:
  - title: "MinWoo Kim"
    image: "assets/images/team/minwoo.png"
    designation: "Project Manager"

  - title: "GyeongMin Jeon"
    image: "assets/images/team/gyeongmin.png"
    designation: "Web Developer"

  - title: "JuYeon Yun"
    image: "assets/images/team/juyeon.png"
    designation: "Web Developer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Project Managing, color: "#fdb157", value: "90%" }
  - { name: Logo Design, color: "#9473e6", value: "60%" }
  - { name: Web Development, color: "#bdecf6", value: "80%" }
  - { name: Web App, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Programming Mentor,
      icon: "icon-1.png",
      date: "Jan 2020 - Aug 2021",
      organization: "903",
    }
  - {
      name: Web Developer & Mentor,
      icon: "icon-2.png",
      date: "Sep 2021 - Present",
      organization: "With Math&English",
    }
  - {
      name: Program Developer,
      icon: "icon-3.png",
      date: "Feb 2020 - Present",
      organization: "DKU University",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Graduated Elementary School,
      date: "2013",
      organization: "Incheon Nonhyeon Elementary School",
    }
  - {
      name: Graduated Middle School,
      date: "2016",
      organization: "Incheon Nonhyeon Middle School",
    }
  - {
      name: Graduated High School,
      date: "2019",
      organization: "Kojan High School",
    }
  - {
      name: enter university on a scholarship,
      date: "2020",
      organization: "Dankook University",
    }

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: Logo Design,
      icon: ti-palette,
      description: "I've studied logo design for two years, and I'm confident in the geometric design of shapes and lines. If you want a simple but clear message, here.",
      active: ,# Add true to select section
    }
  - {
      name: Client Development,
      icon: ti-vector,
      description: "This is the field wee have studied the longest, and if you want to develop a delicate client, I can recommend our team with the most confidence. Our team has extensive experience from games based on Unreal Engine to developing basic websites and IOS applications.",
      active: true, # Add true to select section
    }
  - {
      name: Project Managing,
      icon: ti-panel,
      description: "Is it difficult to communicate with your team members? Do you have a lot of experience where you miss the flow every day when you start a project? Project Manager can solve all of these problems.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:

  - image: "assets/images/portfolio/item-4.png"
    url: "https://github.com/chalgul/EscapeofDominic"


# Portfolio Page
portfolio-label:
  - { title: "Development", type: "development" }

portfolio-items:
  - image: "assets/images/portfolio/item-5.png"
    url: "https://github.com/chalgul/EscapeofDominic"
    portfolio-type:
      - type: "development"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
